# Generated by Django 5.2.17 on 2026-09-22 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='Enlace al gestor de contraseñas')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client_visible', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contract', 'Contrato'), ('gdpr', 'Encargo de tratamiento RGPD'), ('estimate', 'Presupuesto'), ('other', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichero')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('signed', 'Firmado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceptada'), ('in_progress', 'En desarrollo'), ('testing', 'En pruebas'), ('production', 'En producción'), ('rejected', 'Rechazada')], default='requested', max_length=30, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Alta'), ('low', 'Baja')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Fecha objetivo')),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Dominio')),
                ('repository', models.URLField(blank=True, verbose_name='Repositorio')),
                ('launched_at', models.DateTimeField(blank=True, null=True, verbose_name='Puesta en producción')),
                ('monitoring_enabled', models.BooleanField(default=False, verbose_name='Monitorización activada')),
                ('incident_open', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business',), name='one_website_per_business')],
            },
        ),
    ]
