# Generated by Django 5.2.17 on 2026-09-22 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesslink_activityevent_document_request_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('changes', 'Cambios pedidos'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida hasta')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='request',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.proposal'),
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('development_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desarrollo')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mantenimiento mensual')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client_comment', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_method', models.CharField(blank=True, max_length=30)),
                ('acceptance_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.proposal')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe')),
                ('included', models.BooleanField(default=False, verbose_name='Incluido')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.proposalversion')),
            ],
        ),
        migrations.CreateModel(
            name='StageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('found', 'Encontrado'), ('visited', 'Visitado'), ('profile_created', 'Ficha creada'), ('proposal', 'Propuesta'), ('review', 'Revisión'), ('approved', 'Presupuesto aprobado'), ('development', 'Desarrollo'), ('testing', 'Pruebas'), ('production', 'Producción'), ('discarded', 'Descartado')], max_length=30)),
                ('to_stage', models.CharField(choices=[('found', 'Encontrado'), ('visited', 'Visitado'), ('profile_created', 'Ficha creada'), ('proposal', 'Propuesta'), ('review', 'Revisión'), ('approved', 'Presupuesto aprobado'), ('development', 'Desarrollo'), ('testing', 'Pruebas'), ('production', 'Producción'), ('discarded', 'Descartado')], max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.UniqueConstraint(fields=('proposal', 'number'), name='unique_proposal_version'),
        ),
    ]
