# Generated by Django 5.2.17 on 2026-09-22 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_immutable_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('requests', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('included_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo Google')),
                ('query', models.CharField(blank=True, max_length=200, verbose_name='Texto de búsqueda')),
                ('color', models.CharField(choices=[('yellow', 'yellow'), ('pink', 'pink'), ('green', 'green'), ('blue', 'blue'), ('purple', 'purple'), ('teal', 'teal'), ('gray', 'gray')], default='blue', max_length=20, verbose_name='Color')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=20)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('radius', models.PositiveIntegerField(default=1000, verbose_name='Radio (m)')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('kind', models.CharField(choices=[('visit', 'Visita'), ('call', 'Llamada'), ('proposal', 'Propuesta'), ('collection', 'Cobro'), ('renewal', 'Renovación')], max_length=20, verbose_name='Tipo')),
                ('done', models.BooleanField(default=False, verbose_name='Hecho')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('primary_type', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('has_website', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('photos', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('maps_url', models.URLField(blank=True, max_length=1000)),
                ('business_status', models.CharField(default='OPERATIONAL', max_length=40)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opportunity_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('pipeline', 'En pipeline'), ('discarded', 'Descartado')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.searchcategory')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.searchzone')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('result', models.CharField(max_length=200, verbose_name='Resultado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
