# Generated by Django 5.2.17 on 2026-09-22 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_placesusage_searchcategory_searchrun_searchzone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe')),
                ('periodicity', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Periodicidad')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Próxima fecha')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('kind', models.CharField(choices=[('development', 'Desarrollo'), ('maintenance', 'Mantenimiento'), ('domain', 'Dominio'), ('hosting', 'Hosting'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe')),
                ('included', models.BooleanField(default=False, verbose_name='Incluido')),
                ('periodicity', models.CharField(choices=[('once', 'Única'), ('monthly', 'Mensual'), ('annual', 'Anual')], default='once', max_length=20, verbose_name='Periodicidad')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Próxima fecha')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=20, verbose_name='Estado de pago')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('concept', models.CharField(max_length=250, verbose_name='Concepto')),
                ('category', models.CharField(choices=[('development', 'Desarrollo'), ('maintenance', 'Mantenimiento'), ('domain', 'Dominio'), ('hosting', 'Hosting'), ('tools', 'Herramientas'), ('materials', 'Material'), ('commission', 'Comisión'), ('tax', 'Impuestos'), ('other', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe con signo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Justificante')),
                ('source_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=200, verbose_name='Beneficiario')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe fijo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada')], default='pending', max_length=20, verbose_name='Estado')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fixed_amount__isnull', True), ('percentage__isnull', False)), models.Q(('fixed_amount__isnull', False), ('percentage__isnull', True)), _connector='OR'), name='commission_one_amount')],
            },
        ),
    ]
