# Generated by Django 5.2.17 on 2026-09-22 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificationreceipt_recurringexpense_clientcharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('recipients', models.JSONField(default=list)),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='historical_status',
            field=models.CharField(blank=True, choices=[('changes', 'Cambios pedidos'), ('accepted', 'Aceptada')], max_length=20),
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
            options={
                'indexes': [models.Index(fields=['website', '-checked_at'], name='core_uptime_website_b826c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UptimeDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checks', models.PositiveIntegerField()),
                ('failures', models.PositiveIntegerField()),
                ('availability', models.DecimalField(decimal_places=3, max_digits=6)),
                ('average_latency', models.DecimalField(decimal_places=2, max_digits=12)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('website', 'date'), name='unique_uptime_day')],
            },
        ),
    ]
